### ISSUE TITLE
Different From address in SMTP envelope

### ISSUE THREAD

**Issue by rtieland** [axuno/MailMergeLib#13]
Is it possible to implement an option to have different from address in the from header of the message and the SMTP envelope.  This to implement a way for bounced mails to be delivered to an other address.

the Return-Path header wil eventually be filled with the different from address.

for more information about this scenario see https://tools.ietf.org/html/rfc5321#section-4.4

**Comment by axunonb** [comment]
Do I understand right you're saying that
```
var mmm = new MailMergeMessage();
mmm.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.From, "test1@my.sample"));
mmm.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.From, "test2@my.sample"));
```
does not lead to the result you expect?

**Comment by rtieland** [comment]
Unfortunately It doesn't.

I am expecting the following conversation with a smtp server:

S: 220 smtp.example.com ESMTP Postfix
C: HELO relay.example.com
S: 250 smtp.example.com, I am glad to meet you
**C: MAIL FROM:<theboss@example.com>**
S: 250 Ok
C: RCPT TO:<alice@example.com>
S: 250 Ok
C: DATA
S: 354 End data with <CR><LF>.<CR><LF>
**C: From: "Bob Example" <bob@example.com>**
C: To: Alice Example <alice@example.com>
C: Date: Tue, 15 January 2008 16:02:43 -0500
C: Subject: Test message
C: 
C: Hello Alice.
C: This is a test message with 5 header fields and 4 lines in the message body.
C: Your friend,
C: Bob
C: .
S: 250 Ok: queued as 12345
C: QUIT
S: 221 Bye

As you can see the From in the DATA block (bob@example.com) is different from the MAIL FROM value (theboss@example.com).

**Comment by axunonb** [comment]
The ```MAIL FROM``` won't help you at all for bounce management, because it does not become part of the mail message. ```MailMergeSender``` uses the first ```MailAddressType.From``` from the ```MailMergeAddressCollection``` for the SMTP protocol. Some SMTP servers add the authenticated user (coming from credentials) as the ```X-AuthUser: user@some.domain``` header, though.

For bounces you'll have to use a custom header like this:
```mmm.Headers.Insert(0, HeaderId.ReturnPath, "any-bounce-address@some.domain");```.
Note: Some SMTP servers override this header with the authenticated user address coming from the server login.

So for mail messages its necessary to distinguish between

- SMTP protocol before the DATA command (between ```MailMergeSender``` as the client and the SMTP server), which has nothing to do with the message itsself
- The message headers
- The message body (text, HTML, attachments)

**Comment by axunonb** [comment]
@rtieland: Was this of any help?
