### ISSUE TITLE
Support .NET Core?

### ISSUE THREAD

**Issue by thangchung** [axuno/MailMergeLib#2]
Hi there, 
I just read the article at http://www.codeproject.com/Articles/1136943/Understanding-Retry-Pattern-with-Exponential-back using the MailMergeLib and found out this repo. This is a good lib. But my question is do you have a plan to upgrade it to .NET Core?

**Comment by axunonb** [comment]
The underlying libraries all support .NET Core, so building MailMergeLib for .NET Core should be possible without too much effort. It's not on the priorities' list yet, though.

If you want to adjust the dependencies in the nuspec / project then feel free to do so. Any PR on this is highly appreciated.

**Comment by axunonb** [comment]
Had a closer look today and it seems like my fist assumption was kind of very optimistic.
Need to rethink .NET Core in the future.

**Comment by axunonb** [comment]
So: a first port to .NETStandard 1.6 worked as a proof of concept with the following dependencies:
"AngleSharp": "0.9.9
"MailKit": "1.8.1"
"MimeKit": "1.8.0"
"Microsoft.Extensions.Configuration.Xml": "1.0.0"
"NETStandard.Library": "1.6.0"
"System.Collections.Specialized": "4.0.1"
"System.Data.Common": "4.1.0"
"System.IO.FileSystem": "4.0.1"
"System.Runtime": "4.1.0"
"System.Threading.Thread": "4.0.0"
There were a couple of changes necessary in the code because of missing ports from .NET Framework 4.x, which were not too difficult, but still subject to some testing. 
Still struggling with System.Runtime.Remoting.Messaging / CallContext.LogicalGetData() and CallContext.LogicalSetData() from SmartFormat.NET.
Any contributions still welcome.

**Comment by axunonb** [comment]
@thangchung: MailMergeLib 5.1.0.0 supports .Net Core (NET Standard 1.6)

**Comment by thangchung** [comment]
@axunonb Lovely. I just added your very excellent lib into [my repo](https://github.com/thangchung/awesome-dotnet-core) so that everyone can use it in their projects. Thanks so much.

**Comment by axunonb** [comment]
@thangchung Thank you! I had a closer look at your repo and it contains a lot of valuable projects, quite some I was not aware of before. Keep it up!
