### ISSUE TITLE
send mail thru gmail server

### ISSUE THREAD

**Issue by eddylai** [axuno/MailMergeLib#8]
tried to send mail thru gmail server got 
5.7.0 Must issue a STARTTLS command first! error

**Comment by axunonb** [comment]
Thanks the hint. It would be best if you supplied the relevant code snippet, especially concerning the settings of your ```SmtpClientConfig``` settings in order to figure out possible reasons.

**Comment by eddylai** [comment]
var mms = new MailMergeSender();
            mms.Config.MaxNumOfSmtpClients = 1;  // enough for a single email
            mms.Config.SmtpClientConfig[0].MessageOutput = MessageOutput.SmtpServer;
            mms.Config.SmtpClientConfig[0].ClientDomain = "gmail.com";
            mms.Config.SmtpClientConfig[0].SmtpHost = txtSendServer.Text;
            mms.Config.SmtpClientConfig[0].SmtpPort = 587;
            mms.Config.SmtpClientConfig[0].SecureSocketOptions = MailKit.Security.SecureSocketOptions.Auto;
            mms.Config.SmtpClientConfig[0].Timeout = 100000;
            mms.Config.SmtpClientConfig[0].NetworkCredential = new Credential(txtSendID.Text, txtSendPwd.Text);
            mms.Config.SmtpClientConfig[0].MaxFailures = 3;
            mms.Send(mmm, variables);

the host is set to "smtp.gmail.com", and ID,Password is my gmail id/password

**Comment by axunonb** [comment]
Assuming there is nothing wrong with the ```MailMergeMessage``` everything is fine with the code snippet. Please note: ```ClientDomain``` sets the local machine name.
With Gmail using TLS port 587 ```SecureSocketOptions.StartTls``` would be better than ```SecureSocketOptions.Auto```.

In order to use Gmail SMTP you have to enable so-called "Access for less secure apps" in your Google account (https://www.google.com/settings/security/lesssecureapps). Otherwise you will end up with an ```AuthenticationException```. With this in place my test worked just fine.

Something to consider: As far as I remember, Google limits SMTP mails to a certain number recipients at a time and a certain number of messages per day. The number of concurrent connections is limited as well. So Gmail is not the best choice for using ```MailMergeLib``` in a larger scale.

**Comment by axunonb** [comment]
Do you have it working with Gmail now?
